MyPet-Sparta5/Mypet-front

src/App.js
src/components/Login.jsx
src/pages/LoginPage.jsx
src/styles/App.css
src/styles/Login.module.css

[2024/07/22]feat/#3 login front

---

src/App.js
src/components/Signup.jsx
src/pages/SignupPage.jsx
src/styles/Signup.module.css

[2024/07/22]feat/#7 signup front

---

src/App.js
src/components/PostList.jsx
src/pages/PostListPage.jsx
src/styles/PostList.module.css

[2024/07/22]feat/#8 posts front

---

package-lock.json
package.json
src/App.js
src/components/Comment.jsx
src/components/PostDetail.jsx
src/components/PostList.jsx
src/context/PostContext.jsx
src/pages/PostDetailPage.jsx
src/styles/PostDetail.module.css

#11 
자유게시글 조회 화면 구성
댓글, 좋아요 부분도 화면 구성
>

[2024/07/23]feat/#11 freedom post front

---

src/components/PostDetail.jsx
src/components/PostEditModal.jsx
src/styles/Modal.module.css

[2024/07/23]feat/#14 post edit modal

---

src/components/DeleteModal.jsx
src/components/PostDetail.jsx

[2024/07/23]feat/#15 post delete modal

---

package-lock.json
package.json
src/App.js
src/components/DeleteModal.jsx
src/components/ImageSlider.jsx
src/components/PetCardPost.jsx
src/components/PostDetail.jsx
src/components/PostList.jsx
src/components/ReportModal.jsx
src/context/PostContext.jsx
src/pages/PetCardPostPage.jsx
src/styles/ImageSlider.module.css
src/styles/Modal.module.css
src/styles/PetCardPost.css
src/styles/PostDetail.module.css

#12 
자랑하기 게시물 화면 구성 및 통합게시판에서 카테고리별 게시물 화면으로 이동되도록 수정함.
>

[2024/07/24]feat/#12 pet post detail

---

src/components/PetCardPost.jsx

[#22]✨feat : 자랑하기 게시물 수정 모달 연결

---

src/components/PetCardPost.jsx

[2024/07/24]feat/#23 pet post delete modal

---

src/components/DropdownMenu.jsx
src/components/Header.jsx
src/styles/DropdownMenu.module.css
src/styles/Header.module.css

[2024/07/25]feat/#21 user menu

---

.gitignore
public/index.html
src/App.js
src/components/Header.jsx
src/pages/FacilityFinderPage.jsx
src/styles/FacilityFinderPage.css

> #2
> 카카오 맵 띄우기
> 서버에서 데이터 받아서 마커 표시
>

[2024/07/25]feat/#2 kakao map api

---

src/styles/Header.module.css

[2024/07/25]fix/#50 header css

---

src/components/ImageSlider.jsx
src/components/PetCardPost.jsx
src/components/PostDetail.jsx
src/components/PostList.jsx

> ex) #37
통합 게시판 페이지 버튼 동적으로 보여주도록 수정했습니다.
사진이 정상적으로 보입니다.
자유게시글이 보입니다. 댓글은 빈 배열로 연결해뒀습니다.

[2024/07/25]feat/#37 boast detail feat

---

src/styles/PostList.module.css

> ex) #55
> 카테고리 간격 줄이고 제목 간격 넓혔습니다

[2024/07/25]refactor/#55-postList-css

---

src/components/Signup.jsx

#31 
회원가입 페이지에서 백앤드 서버의 회원가입 API 와 연동
>

[2024/07/25]feat/#31 link signup backend

---

src/App.js
src/components/AdminHeader.jsx
src/components/ReportList.jsx
src/pages/Admin/AdminReportListPage.jsx
src/styles/PostList.module.css
src/styles/ReportList.module.css
src/styles/UserList.module.css

> ex) #45 
> 신고 게시판 목록 구현
> 어드민 헤더 간격 수정

[2024/07/25]feat/#45 reports backoffice front

---

src/App.js
src/components/AdminHeader.jsx
src/components/DropdownMenu.jsx
src/components/ReportList.jsx
src/styles/AdminHeader.module.css

#60
백오피스 URL 수정
드롭다운 백오피스 URL 연동

[2024/07/26]fix/#60 admin header fix

---

src/components/PostCreateModal.jsx
src/components/PostList.jsx
src/styles/PostList.module.css

> ex) #58
통합게시판에서 글 추가 버튼 생성시 카테고리 선택 기능
자랑 게시판 / 자유 게시판은 카테고리 고정
> 버튼 디자인을 못하겠어요.... 도와주실 분 구함니다.. 아님 나중에 수정해도 괜찮을거같아요!

[2024/07/26] feat/#58 post create front

---

src/components/ReportList.jsx
src/components/ReportStatusModal.jsx
src/components/UserList.jsx
src/components/UserRoleModal.jsx
src/components/UserStatusModal.jsx
src/styles/DropdownMenu.module.css

#44 
각각 모달 구현
카카오맵 위에 드롭박스가 뜨도록 수정
>

[2024/07/26] feat/#44 backoffice modal feat

---

src/components/PostCreateModal.jsx

#66
프론트에 게시물 작성 API 연동작업했습니다.
> 저장한 데이터를 콜백해서 작성한 게시물이 바로 화면에 표시되게 하려했으나
작동하지않아서 작성시 페이지가 새로고침되서 게시물이 보일수있도록 했습니다.

[2024/07/28]feat/#66 게시물 작성 API 연동

---

src/components/UserList.jsx
src/components/UserRoleModal.jsx
src/components/UserStatusModal.jsx
src/styles/UserList.module.css

#28 
유저리스트 조회 연동
유저 권한 변경 연동
유저 상태 변경 연동
>

[2024/07/29]feat/#28 userpage backend

---

src/components/PostDetail.jsx
src/styles/PostDetail.module.css

> #27
> 댓글 확인하기 연동
> 댓글 작성하기 연동
> 댓글 삭제하기 연동

[2024/07/29]feat/#27 comment

---

src/components/PetCardPost.jsx
src/components/PostDetail.jsx

[2024/07/29]feat/#68 post update back

---

src/components/LikeButton.jsx
src/components/PetCardPost.jsx
src/components/PostDetail.jsx
src/styles/LikeButton.module.css
src/styles/PostDetail.module.css

> #30 
> 좋아요 연동
>
> LikeButton을 분리하니 자랑하기 게시판에서는 좋아요가 왼쪽으로 갔는데 수정을 못하고 올렸습니다.
> post를 set만 해주고 사용하지않아서 대부분의 변수를 없애고 post에서 접근해서 사용하도록 변경했습니다.

[2024/07/29]feat/#30 post detail like

---

src/components/UserList.jsx

#75 
userList 조회시 토큰 만료일때 재발급 하는 부분 추가
>

[2024/07/29]fix/#75 userList refreshToken

---

src/components/PetCardPost.jsx
src/components/PostDetail.jsx

[2024/07/29]feat/#69 post delete

---

src/components/PetCardPost.jsx
src/components/PostDetail.jsx
src/components/ReportModal.jsx

#80 
1. 유저 신고 기능 연동
2. 아이콘 조건부 렌더링 추가
비회원 / 내가 쓴 글이 아닐 경우 신고 아이콘만 보이도록 수정
본인이 쓴 글에서 수정,삭제 아이콘 노출
> 백엔드 코드에서 postResponseDto가 수정되어 곧 pr올릴 예정입니다.
merge 이후 프론트, 백 모두 pull 한번씩 받아주세요.

[2024/07/29] feat/#80 user report backend

---

src/components/LikeButton.jsx
src/components/Login.jsx
src/components/Logout.jsx
src/components/PetCardPost.jsx
src/components/PostCreateModal.jsx
src/components/PostDetail.jsx
src/components/UserList.jsx
src/components/refreshToken.jsx

#73 
- RefreshToken 컴포넌트 이름과 함수 이름 리펙토링 
- RefreshToken 재발급 실패 시, 프론트 `logout` 시키고 로그인 페이지로 이동하도록 수정
- RefreshToken 함수 수정된 내용을 사용부에 적용
>

[2024/07/30]refactor/#73 auth refresh token

---

src/components/PetCardPost.jsx
src/components/PostDetail.jsx

> #83 
Admin, Manager에 사용자 게시물 삭제 권한 부여
PetCardPost 수정
PostDetail 수정

[2024/07/30] fix/#83 Admin, Manager에 사용자 게시물 삭제 권한 부여

---

src/App.js
src/components/ChangePasswordModal.jsx
src/components/Profile.jsx
src/components/UserEditModal.jsx
src/components/WithdrawModal.jsx
src/pages/ProfilePage.jsx
src/styles/Modal.module.css
src/styles/Profile.module.css

#76 
오류 발생시 모달 내에서 +1px, Bold, Red 옵션으로 오류 메시지를 보여줬습니다.

[2024/07/30]feat/#76 mypage front

---

src/components/ReportList.jsx
src/components/ReportStatusModal.jsx
src/styles/ReportList.module.css

[2024/07/30]feat/#29 report page backend

---

src/components/UserRoleModal.jsx
src/components/UserStatusModal.jsx
src/styles/Modal.module.css

#88 
누락된 css style 변경했습니다.
=>
>

[2024/07/30]style/#88 modal style

---

src/components/PostCreateModal.jsx
src/components/PostList.jsx

#91
file -> files로 RequestPart명 변경
API 호출 위치 postList 로 이동
게시글 생성시 상세 페이지로 navigate

[2024/07/30] fix/#91 postcreatemodal files

---

src/App.js
src/ProtectedRoute.jsx
src/pages/AccessDeniedPage.jsx

#95 
admin, manager권한만 backoffice 접근 가능하도록 함.
기존 > 
변경후 > 
>

[2024/07/30]refactor/#95 AccessDeniedPage

---

src/components/UserList.jsx

#93  
Manager 권한이 useRole edit modal 클릭시 접근불가 alert 띄우기 
>

[2024/07/30]fix/#93 userRole edit modal

---

src/components/PetCardPost.jsx
src/components/PostDetail.jsx
src/components/PostList.jsx

> ex) #이슈번호, #이슈번호  
#94
> 이번 PR에서 작업한 내용을 간략히 설명해주세요 (이미지 첨부 가능)
1. **비회원이 게시물 조회 시**
- **자유게시글:** 
- 댓글 작성 불가
- 수정, 삭제, 신고 아이콘이 보이지 않음
- **자랑게시글:** 
- 수정, 삭제, 신고 아이콘이 보이지 않음
- (댓글은 비회원만 작성할 수 없음)
2. **회원이 게시물 조회 시**
- **본인이 작성한 자유/자랑 게시글:**
- 수정, 삭제 아이콘 보임
- **본인이 작성하지 않은 자유/자랑 게시글:** 
- 신고 아이콘 보임
3. **어드민, 매니저가 게시물 조회 시**
- **본인이 작성한 자유/자랑 게시글:**
- 수정, 삭제 아이콘 보임
- **본인이 작성하지 않은 자유/자랑 게시글:**
- 삭제 아이콘 보임

 [2024/07/30]refactor /#94 post icon

---

src/components/ChangePasswordModal.jsx
src/components/DropdownMenu.jsx
src/components/Logout.jsx
src/components/Profile.jsx
src/components/UserEditModal.jsx
src/styles/Profile.module.css

#32 
- 마이페이지에 사용자 정보 받아오는 기능 연동
- 회원 정보 수정 기능 연동
- 비밀번호 수정  기능 연동
- 회원 탈퇴 기능 연동
- 자신의 게시물에 게시물 디테일 페이지로 연결
>
로그아웃에 `navigate` 기능과 `alert` 제거했습니다.  로그아웃하는 기능만 되어 있기 때문에 사용하는 부분에서 로그아웃 후 작업을 명시해서 사용하시면 됩니다.

[2024/07/31]feat/#32 link mypage backend

---

src/components/ReportList.jsx
src/styles/ReportList.module.css

#99 
- reportList nickname을 email로 변경 
- 테이블 순서 userList처럼 마지막에 일자 나오도록 변경
>

[2024/07/31]refactor/#99 reportList nickname to email

---

src/components/DropdownMenu.jsx
src/components/Profile.jsx
src/styles/DropdownMenu.module.css

#103 
- 새로운 닉네임으로 localStorage 업데이트
- 드롭다운메뉴에서 my page 선택 시, 페이지 열리고 드롭다운메뉴 토글
>

[2024/07/31]fix/#103 profile user update

---

src/App.js
src/components/AdminHeader.jsx
src/pages/Admin/AdminPostListPage.jsx
src/pages/Admin/AdminSuspensionListPage.jsx

#110 
admin header에 navigation 추가 및 페이지 추가
>

[2024/08/01]refactor/#110 admin header addNavigation

---

src/components/AdminPostList.jsx
src/pages/Admin/AdminPostListPage.jsx
src/styles/PostList.module.css

#113 
backoffice admin post list 화면 구성입니다.
>

[2024/08/01]feat/#113 admin post list

---

src/components/AdminPostList.jsx
src/components/PostStatusModal.jsx
src/styles/PostList.module.css

#114 
백오피스 admin post status 변경 modal 추가
post 제목 누르면 post detail로 / status 누르면 post status modal이 뜨도록 수정
>

[2024/08/01] feat/#114 admin post status modal

---

src/components/SuspensionList.jsx
src/pages/Admin/AdminSuspensionListPage.jsx
src/styles/SuspensionList.module.css

#112 
백오피스 - 유저 정지 목록 조회 화면 구상
>

[2024/08/01]feat/#112 user suspension list

---

src/components/PetCardPost.jsx
src/components/PostDetail.jsx

#118 
신고 API를 백엔드가 리펙터함에 따라 수정했습니다.
>

[2024/08/01]refactor /#118 report post id

---

src/components/AdminPostList.jsx
src/components/PostDetail.jsx
src/components/PostStatusModal.jsx

#120 
admin Post List Page 백엔드 연동
>

[#120]✨feat : adminpostList 연결

---

src/components/AdminPostList.jsx

#125 
adminPostList에서 포스트 디테일로 넘어가는 부분 카테고리별로 정상적으로 나오도록 수정
>

[2024/08/02]refactor/#125 adminPostList navigate edit

---

src/components/UserList.jsx
src/components/UserStatusModal.jsx

#128 
유저 정지로 상태 변경할 때 정지 사유 작성하는 칸 나오도록 변경
>

[2024/08/05]refactor/#128 user suspension issue

---

src/components/Login.jsx
src/components/Signup.jsx

[2024/08/05]refactor/#130 alert update user

---

src/components/ReportList.jsx
src/components/UserList.jsx
src/styles/ReportList.module.css
src/styles/UserList.module.css

#132 
userList, reportList userId 추가
>

[2024/08/05]refactor/#132 userList reportList userId

---

src/components/AdminPostList.jsx
src/components/PostList.jsx

[2024/08/06]refactor/#134 postListResponseDto

---

src/components/Profile.jsx

[2024/08/07] #138 email bug fix

---

set.Proxy.js
src/components/AdminPostList.jsx
src/components/KakaoLinkCallback.jsx
src/components/KakaoLoginCallback.jsx
src/components/LikeButton.jsx
src/components/Login.jsx
src/components/Logout.jsx
src/components/MyPostList.jsx
src/components/PetCardPost.jsx
src/components/PostDetail.jsx
src/components/PostList.jsx
src/components/Profile.jsx
src/components/RefreshToken.jsx
src/components/ReportList.jsx
src/components/Signup.jsx
src/components/SuspensionList.jsx
src/components/UserList.jsx
src/pages/FacilityFinderPage.jsx
src/setting/api.js

#140 
api.js로 기본 설정값 합쳤습니다.
>
전체적으로 잘 돌아가는 것 확인했는데 다시 한번 작업했던 부분 한번씩만 더 봐주세요!

[2024/08/08]refactor/#140 baseUrl Authorization Refreshtoken

---

src/components/DropdownMenu.jsx
src/components/Profile.jsx
src/styles/Profile.module.css

#137 
서버의 getUser 로직의 분리로 인해, 프론트에서 유저 정보를 하나로 호출했던 부분을 두가지 API를 호출하도록 수정
>

[2024/08/08]refactor/#137 separate profile information

---

src/components/Signup.jsx
src/styles/Signup.module.css

> #143
> 회원가입 페이지에 이메일 인증 기능 연결
>

[2024/08/08]#143 signup page update

---

src/components/ImageSlider.jsx
src/styles/ImageSlider.module.css

 [2024/08/08]fix/#145 imageslider

---

src/components/UserList.jsx
src/styles/UserList.module.css

#147 
백오피스 유저리스트 검색기능 연동 및 화면 구성
>

[2024/08/09]feat/#147 backoffice userList search

---

src/components/AdminPostList.jsx
src/components/PetCardPost.jsx
src/components/PostDetail.jsx
src/components/PostStatusModal.jsx

[2024/08/09]refactor/#149 post soft delete

---

package-lock.json
package.json
vercel.json

> #161 
> 리버스 프록시 설정 추가
> vercel.json 파일 추가
>

[2024/08/12] fix : 리버스 프록시 설정 추가

---

vercel.json

[2024/08/12]🔥 del : vercel.json 삭제

---

src/App.js
src/components/MyPostList.jsx
src/components/PostCreateModal.jsx
src/components/PostList.jsx
src/components/Profile.jsx
src/pages/PostListPage.jsx
src/styles/PostList.module.css

#156 
postList 검색기능 추가 및 토큰 없이 조회 가능하도록 수정
돋보기 아이콘을 누르면 검색창이 열립니다.
>

[2024/08/13]feat/#156 postList search

---

src/components/PetCardPost.jsx
src/components/PostDetail.jsx

#169 
댓글 작성 에러 수정 및 로그인 비로그인 상태 분기 처리
>

[2024/08/13]fix/#169 comment error

---

src/components/Signup.jsx

[2024/08/13]fix/#172 signup alert

---

src/components/ReportList.jsx
src/styles/ReportList.module.css

#152 
백오피스 reportList 검색 기능 추가 및 화면 구성
>

[2024/08/13]feat/#152 backoffice reportList search

---

src/App.js
src/pages/FacilityFinderPage.jsx

[2024/08/13]fix/#108 improve map

---

src/components/SuspensionList.jsx
src/styles/SuspensionList.module.css

#153 
백오피스 유저 정지 리스트 검색기능 추가 및 화면 구성
>

[2024/08/13]feat/#153 backoffice suspensionList search

---

src/components/Signup.jsx

> #177
> 이메일 실패 시 처리 수정
> 이메일 전송, 인증 시 로딩 화면 연결
>

[2024/08/14]fix/#177 email verification

---

src/App.js
src/components/Footer.jsx
src/styles/Footer.css

[2024/08/14]feat/#179 footer

---

src/components/PostCreateModal.jsx

 [2024/08/14]refactor/#182 file error

---

src/components/PostList.jsx

[2024/08/14]fix/#189 createmodal alert

---

src/components/Profile.jsx

#191 
mypage delete post 안보이도록 수정
>

[2024/08/16] fix/#191 mypage delete post

---

src/components/Login.jsx

[2024/08/18]fix/#193 login alert

---

src/components/Comment.jsx
src/components/PostDetail.jsx
src/components/PostList.jsx
src/styles/PostDetail.module.css

[2024/08/19]Fix/#196 comment limit

---

src/components/PetCardPost.jsx
src/styles/PetCardPost.css

[2024/08/19]refactor/#202 pet card post refactor

---

src/components/Comment.jsx

> #205
> date-fns을 사용해서 시간대 수정
>

[2024/08/20]hotfix/#205 comment date

---

src/components/Comment.jsx

[2024/08/20]hotfix/#205 comment timezone

---

src/pages/FacilityFinderPage.jsx
src/setting/Loading.js

[2024/08/21]hotfix/#208 map location bug fix
